2020-10-26 08:44:46,817	INFO services.py:1164 -- View the Ray dashboard at [1m[32mhttp://127.0.0.1:8265[39m[22m
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 4: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 4096 current, 1031386 max
Traceback (most recent call last):
  File "main_bound.py", line 8, in <module>
    from synthetic_data import *
  File "/mnt/nfs/work1/cs696/f20pargupta/parallel_exp/synthetic_data.py", line 2, in <module>
    from sklearn.model_selection import train_test_split
  File "/home/f20pargupta/miniconda3/lib/python3.8/site-packages/sklearn/__init__.py", line 80, in <module>
    from .base import clone
  File "/home/f20pargupta/miniconda3/lib/python3.8/site-packages/sklearn/base.py", line 21, in <module>
    from .utils import _IS_32BIT
  File "/home/f20pargupta/miniconda3/lib/python3.8/site-packages/sklearn/utils/__init__.py", line 23, in <module>
    from .class_weight import compute_class_weight, compute_sample_weight
  File "/home/f20pargupta/miniconda3/lib/python3.8/site-packages/sklearn/utils/class_weight.py", line 7, in <module>
    from .validation import _deprecate_positional_args
  File "/home/f20pargupta/miniconda3/lib/python3.8/site-packages/sklearn/utils/validation.py", line 25, in <module>
    from .fixes import _object_dtype_isnan, parse_version
  File "/home/f20pargupta/miniconda3/lib/python3.8/site-packages/sklearn/utils/fixes.py", line 18, in <module>
    import scipy.stats
  File "/home/f20pargupta/miniconda3/lib/python3.8/site-packages/scipy/stats/__init__.py", line 388, in <module>
    from .stats import *
  File "/home/f20pargupta/miniconda3/lib/python3.8/site-packages/scipy/stats/stats.py", line 174, in <module>
    from scipy.spatial.distance import cdist
  File "/home/f20pargupta/miniconda3/lib/python3.8/site-packages/scipy/spatial/__init__.py", line 98, in <module>
    from .qhull import *
  File "<frozen importlib._bootstrap>", line 389, in parent
KeyboardInterrupt
srun: error: swarm051: task 0: Interrupt
